# Generated by Django 2.2.12 on 2021-10-24 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30, null=True, verbose_name='Symbol')),
                ('margin_balance', models.FloatField(blank=True, null=True, verbose_name='账户权益')),
                ('margin_available', models.FloatField(blank=True, null=True, verbose_name='可用保证金')),
                ('margin_position', models.FloatField(blank=True, null=True, verbose_name='已用保证金')),
                ('margin_frozen', models.FloatField(blank=True, null=True, verbose_name='冻结数量')),
                ('profit_real', models.FloatField(blank=True, null=True, verbose_name='已实现盈亏')),
                ('profit_unreal', models.FloatField(blank=True, null=True, verbose_name='未实现盈亏')),
                ('margin_mode', models.CharField(blank=True, max_length=30, null=True, verbose_name='仓位模式')),
                ('max_withdraw', models.FloatField(blank=True, null=True, verbose_name='最大可划转')),
                ('lever_rate', models.FloatField(blank=True, null=True, verbose_name='杠杠倍数')),
                ('open_trade', models.BooleanField(default=True, verbose_name='是否开通交易')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend', models.FloatField(default=1, null=True, verbose_name='趋势')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='名称')),
                ('symbol', models.CharField(blank=True, max_length=30, null=True, verbose_name='期货交易对')),
                ('spot_symbol', models.CharField(blank=True, max_length=30, null=True, verbose_name='现货交易对')),
                ('exchange', models.CharField(db_index=True, max_length=30, null=True, verbose_name='交易所')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('spot_price', models.FloatField(null=True, verbose_name='现货价格')),
                ('swap_price', models.FloatField(null=True, verbose_name='期货价格')),
                ('buy_price', models.FloatField(null=True, verbose_name='买五价格')),
                ('sell_price', models.FloatField(null=True, verbose_name='卖五价格')),
                ('period', models.CharField(choices=[['5min', '5min'], ['15min', '15min'], ['4hour', '4hour']], default='15min', max_length=30, verbose_name='交易周期')),
                ('ma_size', models.IntegerField(default=48, verbose_name='MA SIZE')),
                ('profit_price', models.FloatField(default=0, verbose_name='止盈价格')),
                ('add_size', models.FloatField(default=0.01, verbose_name='补仓')),
                ('qty_size', models.IntegerField(default=100, verbose_name='数量小数位')),
                ('logo', models.CharField(blank=True, max_length=100, null=True, verbose_name='LOGO')),
                ('open_trade', models.BooleanField(default=False, verbose_name='开通交易')),
                ('position', models.IntegerField(blank=True, default=0, verbose_name='当前仓位')),
                ('start_position', models.IntegerField(default=1, verbose_name='实盘仓位')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('target_profit', models.FloatField(default=0.1, null=True, verbose_name='预计月化')),
                ('sync_time', models.DateTimeField(blank=True, null=True, verbose_name='订单同步时间')),
            ],
        ),
        migrations.CreateModel(
            name='CoinPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, max_length=30, null=True, verbose_name='价格')),
                ('volume', models.FloatField(default=0, max_length=30, verbose_name='数量')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='仓位')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仓位',
                'verbose_name_plural': '仓位',
            },
        ),
        migrations.CreateModel(
            name='Ohlcv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(db_index=True, max_length=30, null=True, verbose_name='交易所')),
                ('symbol', models.CharField(db_index=True, max_length=30, verbose_name='交易对')),
                ('period', models.CharField(db_index=True, max_length=30, verbose_name='周期')),
                ('data', models.TextField(verbose_name='数据')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=200, null=True, verbose_name='品种代码')),
                ('trade_id', models.CharField(db_index=True, max_length=200, null=True, verbose_name='成交ID')),
                ('volume', models.FloatField(blank=True, max_length=30, null=True, verbose_name='成交数量')),
                ('commission', models.FloatField(blank=True, default=0, max_length=30, verbose_name='交易费')),
                ('total', models.FloatField(blank=True, max_length=30, null=True, verbose_name='成交额')),
                ('price', models.FloatField(blank=True, max_length=30, null=True, verbose_name='委托价格')),
                ('direction', models.CharField(blank=True, max_length=20, null=True, verbose_name='买卖方向')),
                ('created_at', models.DateTimeField(null=True, verbose_name='成交时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='同步时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='名称')),
                ('code', models.CharField(db_index=True, max_length=30, null=True, verbose_name='策略代码')),
                ('period', models.CharField(choices=[['5min', '5min'], ['15min', '15min']], default='15min', max_length=30, verbose_name='交易周期')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务器IP')),
                ('risk', models.CharField(blank=True, max_length=100, null=True, verbose_name='风险等级')),
                ('tags', models.CharField(max_length=100, null=True, verbose_name='Tag')),
                ('max_users', models.IntegerField(default=0, verbose_name='最大参与人数')),
                ('status', models.BooleanField(default=False, verbose_name='是否开启')),
                ('state', models.IntegerField(choices=[[0, '未开启'], [1, '进行中'], [2, '已满员']], default=0, verbose_name='状态')),
                ('taget_profit', models.FloatField(default=0, verbose_name='预期月化')),
                ('start_time', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('push_url', models.TextField(blank=True, null=True, verbose_name='推送链接')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leverage', models.IntegerField(default=0, verbose_name='杠杠')),
                ('symbol', models.CharField(db_index=True, max_length=30, null=True, verbose_name='交易对')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='代码')),
                ('period', models.CharField(blank=True, max_length=30, null=True, verbose_name='周期')),
                ('strategy', models.CharField(blank=True, max_length=30, null=True, verbose_name='策略')),
                ('exchange', models.CharField(db_index=True, max_length=30, null=True, verbose_name='交易所')),
                ('price', models.FloatField(blank=True, max_length=30, null=True, verbose_name='平均价格')),
                ('best_price', models.FloatField(blank=True, max_length=30, null=True, verbose_name='委托价格')),
                ('init_price', models.FloatField(default=0, max_length=30, null=True, verbose_name='开单价格')),
                ('last_price', models.FloatField(default=0, max_length=30, null=True, verbose_name='加仓价格')),
                ('profit', models.FloatField(blank=True, max_length=30, null=True, verbose_name='利润')),
                ('action', models.CharField(choices=[('open', '开'), ('close', '平')], max_length=100, null=True, verbose_name='交易')),
                ('direction', models.CharField(choices=[('long', '多'), ('short', '空')], max_length=30, null=True, verbose_name='方向')),
                ('featured', models.BooleanField(default=False, verbose_name='案例信号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quant.Coin')),
            ],
            options={
                'verbose_name': '信号',
                'verbose_name_plural': '信号',
            },
        ),
    ]
