# Generated by Django 2.2.12 on 2021-10-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0002_auto_20211024_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
